/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EksportRouteImport } from './routes/eksport'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as ZadaniaRouteImport } from './routes/zadania'
import { Route as ZmianaHaslaRouteImport } from './routes/zmiana-hasla'
import { Route as AdminUrzadzeniaRouteImport } from './routes/admin.urzadzenia'
import { Route as AdminUzytkownicyRouteImport } from './routes/admin.uzytkownicy'
import { Route as AwarieIndexRouteImport } from './routes/awarie.index'
import { Route as AwarieIdRouteImport } from './routes/awarie.$id'
import { Route as PrzegladyIndexRouteImport } from './routes/przeglady.index'
import { Route as PrzegladyIdRouteImport } from './routes/przeglady.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EksportRoute = EksportRouteImport.update({
  id: '/eksport',
  path: '/eksport',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const ZadaniaRoute = ZadaniaRouteImport.update({
  id: '/zadania',
  path: '/zadania',
  getParentRoute: () => rootRouteImport,
} as any)
const ZmianaHaslaRoute = ZmianaHaslaRouteImport.update({
  id: '/zmiana-hasla',
  path: '/zmiana-hasla',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUrzadzeniaRoute = AdminUrzadzeniaRouteImport.update({
  id: '/admin/urzadzenia',
  path: '/admin/urzadzenia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUzytkownicyRoute = AdminUzytkownicyRouteImport.update({
  id: '/admin/uzytkownicy',
  path: '/admin/uzytkownicy',
  getParentRoute: () => rootRouteImport,
} as any)
const AwarieIndexRoute = AwarieIndexRouteImport.update({
  id: '/awarie/',
  path: '/awarie/',
  getParentRoute: () => rootRouteImport,
} as any)
const AwarieIdRoute = AwarieIdRouteImport.update({
  id: '/awarie/$id',
  path: '/awarie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrzegladyIndexRoute = PrzegladyIndexRouteImport.update({
  id: '/przeglady/',
  path: '/przeglady/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrzegladyIdRoute = PrzegladyIdRouteImport.update({
  id: '/przeglady/$id',
  path: '/przeglady/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eksport': typeof EksportRoute
  '/logowanie': typeof LogowanieRoute
  '/zadania': typeof ZadaniaRoute
  '/zmiana-hasla': typeof ZmianaHaslaRoute
  '/admin/urzadzenia': typeof AdminUrzadzeniaRoute
  '/admin/uzytkownicy': typeof AdminUzytkownicyRoute
  '/awarie/$id': typeof AwarieIdRoute
  '/przeglady/$id': typeof PrzegladyIdRoute
  '/awarie/': typeof AwarieIndexRoute
  '/przeglady/': typeof PrzegladyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eksport': typeof EksportRoute
  '/logowanie': typeof LogowanieRoute
  '/zadania': typeof ZadaniaRoute
  '/zmiana-hasla': typeof ZmianaHaslaRoute
  '/admin/urzadzenia': typeof AdminUrzadzeniaRoute
  '/admin/uzytkownicy': typeof AdminUzytkownicyRoute
  '/awarie/$id': typeof AwarieIdRoute
  '/przeglady/$id': typeof PrzegladyIdRoute
  '/awarie': typeof AwarieIndexRoute
  '/przeglady': typeof PrzegladyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eksport': typeof EksportRoute
  '/logowanie': typeof LogowanieRoute
  '/zadania': typeof ZadaniaRoute
  '/zmiana-hasla': typeof ZmianaHaslaRoute
  '/admin/urzadzenia': typeof AdminUrzadzeniaRoute
  '/admin/uzytkownicy': typeof AdminUzytkownicyRoute
  '/awarie/$id': typeof AwarieIdRoute
  '/przeglady/$id': typeof PrzegladyIdRoute
  '/awarie/': typeof AwarieIndexRoute
  '/przeglady/': typeof PrzegladyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/eksport'
    | '/logowanie'
    | '/zadania'
    | '/zmiana-hasla'
    | '/admin/urzadzenia'
    | '/admin/uzytkownicy'
    | '/awarie/$id'
    | '/przeglady/$id'
    | '/awarie/'
    | '/przeglady/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/eksport'
    | '/logowanie'
    | '/zadania'
    | '/zmiana-hasla'
    | '/admin/urzadzenia'
    | '/admin/uzytkownicy'
    | '/awarie/$id'
    | '/przeglady/$id'
    | '/awarie'
    | '/przeglady'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/eksport'
    | '/logowanie'
    | '/zadania'
    | '/zmiana-hasla'
    | '/admin/urzadzenia'
    | '/admin/uzytkownicy'
    | '/awarie/$id'
    | '/przeglady/$id'
    | '/awarie/'
    | '/przeglady/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EksportRoute: typeof EksportRoute
  LogowanieRoute: typeof LogowanieRoute
  ZadaniaRoute: typeof ZadaniaRoute
  ZmianaHaslaRoute: typeof ZmianaHaslaRoute
  AdminUrzadzeniaRoute: typeof AdminUrzadzeniaRoute
  AdminUzytkownicyRoute: typeof AdminUzytkownicyRoute
  AwarieIdRoute: typeof AwarieIdRoute
  PrzegladyIdRoute: typeof PrzegladyIdRoute
  AwarieIndexRoute: typeof AwarieIndexRoute
  PrzegladyIndexRoute: typeof PrzegladyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksport': {
      id: '/eksport'
      path: '/eksport'
      fullPath: '/eksport'
      preLoaderRoute: typeof EksportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zadania': {
      id: '/zadania'
      path: '/zadania'
      fullPath: '/zadania'
      preLoaderRoute: typeof ZadaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zmiana-hasla': {
      id: '/zmiana-hasla'
      path: '/zmiana-hasla'
      fullPath: '/zmiana-hasla'
      preLoaderRoute: typeof ZmianaHaslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/urzadzenia': {
      id: '/admin/urzadzenia'
      path: '/admin/urzadzenia'
      fullPath: '/admin/urzadzenia'
      preLoaderRoute: typeof AdminUrzadzeniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uzytkownicy': {
      id: '/admin/uzytkownicy'
      path: '/admin/uzytkownicy'
      fullPath: '/admin/uzytkownicy'
      preLoaderRoute: typeof AdminUzytkownicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awarie/': {
      id: '/awarie/'
      path: '/awarie'
      fullPath: '/awarie/'
      preLoaderRoute: typeof AwarieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awarie/$id': {
      id: '/awarie/$id'
      path: '/awarie/$id'
      fullPath: '/awarie/$id'
      preLoaderRoute: typeof AwarieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/przeglady/': {
      id: '/przeglady/'
      path: '/przeglady'
      fullPath: '/przeglady/'
      preLoaderRoute: typeof PrzegladyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/przeglady/$id': {
      id: '/przeglady/$id'
      path: '/przeglady/$id'
      fullPath: '/przeglady/$id'
      preLoaderRoute: typeof PrzegladyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EksportRoute: EksportRoute,
  LogowanieRoute: LogowanieRoute,
  ZadaniaRoute: ZadaniaRoute,
  ZmianaHaslaRoute: ZmianaHaslaRoute,
  AdminUrzadzeniaRoute: AdminUrzadzeniaRoute,
  AdminUzytkownicyRoute: AdminUzytkownicyRoute,
  AwarieIdRoute: AwarieIdRoute,
  PrzegladyIdRoute: PrzegladyIdRoute,
  AwarieIndexRoute: AwarieIndexRoute,
  PrzegladyIndexRoute: PrzegladyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
